# Build
FROM mcr.microsoft.com/dotnet/sdk:10.0-preview AS build
WORKDIR /src

COPY . .
RUN dotnet restore "PDHours.API/PDHours.API.csproj"
RUN dotnet publish "PDHours.API/PDHours.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Runtime
FROM mcr.microsoft.com/dotnet/aspnet:10.0-preview AS runtime
WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:5022
EXPOSE 5022

ENTRYPOINT ["dotnet", "PDHours.API.dll"]